# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGisFoncier
                                 A QGIS plugin
 Outil de détection des réserves foncières
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-02
        copyright            : (C) 2019 by aurelien andrieu
        email                : aurelien.andrieu@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGisFoncier class from file QGisFoncier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_foncier import QGisFoncier
    return QGisFoncier(iface)
